services:
  spark-master:
    image: apache/spark:3.4.1
    user: root
    working_dir: /workspace
    volumes:
      - ./:/workspace
    ports:
      - 8080:8080
      - 7077:7077
    environment:
      - SPARK_NO_DAEMONIZE=true
    command: ["/opt/spark/sbin/start-master.sh"]

  spark-worker:
    image: apache/spark:3.4.1
    user: root
    working_dir: /workspace
    volumes:
      - ./:/workspace
    depends_on:
      - spark-master
    command: ["/opt/spark/sbin/start-worker.sh", "spark://spark-master:7077"]
    environment:
      - SPARK_NO_DAEMONIZE=true
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=4

  spark-submit:
    image: apache/spark:3.4.1
    user: root
    working_dir: /workspace
    volumes:
      - ./:/workspace
    ports:
      - 4040:4040
    depends_on:
      - spark-master
      - spark-worker
    command: ["/bin/bash", "-c", "tail -f /dev/null"]
    tty: true
